import { Project } from './ProjectCard'

export const mockProjects: Project[] = [
  {
    title: 'TaskMaster Pro',
    description: 'A comprehensive task management system with Pomodoro timer integration, customizable workflows, and data visualization for productivity insights.',
    tech: ['React', 'Node.js', 'MongoDB', 'Express.js', 'Redux'],
    github: 'https://github.com/taskmaster-pro',
    demo: 'https://taskmaster-pro.com',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'EcoShop',
    description: 'An eco-friendly e-commerce platform featuring carbon footprint tracking, sustainable product recommendations, and a recycling rewards program.',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Redux', 'Node.js', 'MongoDB'],
    github: 'https://github.com/ecoshop',
    demo: 'https://ecoshop.com',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'SecureChat',
    description: 'An ultra-secure messaging app with end-to-end encryption, self-destructing messages, and blockchain-based user verification.',
    tech: ['Vue.js', 'Firebase', 'WebRTC', 'Node.js', 'Socket.io', 'Redis'],
    github: 'https://github.com/securechat',
    demo: 'https://securechat.app',
    image: 'https://images.unsplash.com/photo-1587560699334-cc4ff634909a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'MedVision AI',
    description: 'An advanced medical imaging analysis tool using deep learning for early disease detection and personalized treatment planning.',
    tech: ['Python', 'TensorFlow', 'Flask', 'OpenCV', 'NumPy', 'Pandas'],
    github: 'https://github.com/medvision-ai',
    demo: 'https://medvision.ai',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'SupplyChain+',
    description: 'A decentralized supply chain management platform with real-time tracking, smart contract automation, and predictive analytics for inventory optimization.',
    tech: ['Solidity', 'Ethereum', 'Web3.js', 'React', 'Node.js', 'MongoDB'],
    github: 'https://github.com/supplychain-plus',
    demo: 'https://supplychain-plus.io',
    image: 'https://images.unsplash.com/photo-1566843972142-a7fcb70de55a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'SmartHome Hub',
    description: 'A centralized IoT platform for managing smart home devices, featuring voice control, energy optimization, and predictive maintenance.',
    tech: ['React Native', 'AWS IoT', 'GraphQL', 'Node.js', 'MongoDB', 'Redis'],
    github: 'https://github.com/smarthome-hub',
    demo: 'https://smarthome-hub.io',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'FitnessFusion',
    description: 'An AI-powered fitness app offering personalized workout plans, nutrition tracking, and virtual reality training sessions.',
    tech: ['Flutter', 'TensorFlow Lite', 'Firebase', 'Node.js', 'MongoDB', 'Redis'],
    github: 'https://github.com/fitnessfusion',
    demo: 'https://fitnessfusion.app',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'CryptoTax',
    description: 'A cryptocurrency tax calculation and reporting tool, supporting multiple exchanges and providing real-time tax liability estimates.',
    tech: ['Angular', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    github: 'https://github.com/cryptotax',
    demo: 'https://cryptotax.io',
    image: 'https://images.unsplash.com/photo-1621504450181-5d356f61d307?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'EduQuest',
    description: 'An interactive e-learning platform with gamification elements, adaptive learning paths, and real-time collaboration features.',
    tech: ['React', 'Express.js', 'MongoDB', 'Socket.io', 'Redis', 'AWS'],
    github: 'https://github.com/eduquest',
    demo: 'https://eduquest.com',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'GreenCity',
    description: 'A smart city management system focusing on sustainability, featuring pollution monitoring, waste management optimization, and citizen engagement tools.',
    tech: ['Vue.js', 'Django', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
    github: 'https://github.com/greencity',
    demo: 'https://greencity.io',
    image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  },
  {
    title: 'ArtificialMind',
    description: 'A cutting-edge artificial general intelligence research platform, combining neural networks, evolutionary algorithms, and cognitive architectures.',
    tech: ['Python', 'PyTorch', 'Ray', 'TensorFlow', 'Scikit-learn', 'Docker'],
    github: 'https://github.com/artificialmind',
    demo: 'https://artificialmind.ai',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=400&h=300',
  }
]
