import { Project } from './ProjectCard'

export const mockProjects: Project[] = [
  {
    title: 'TaskMaster Pro',
    description: 'A comprehensive task management system with Pomodoro timer integration, customizable workflows, and data visualization for productivity insights.',
    tech: ['React', 'Node.js', 'MongoDB'],
    github: 'https://github.com/taskmaster-pro',
    demo: 'https://taskmaster-pro.com',
    image: 'https://picsum.photos/seed/TaskMasterPro/400/300',
  },
  {
    title: 'EcoShop',
    description: 'An eco-friendly e-commerce platform featuring carbon footprint tracking, sustainable product recommendations, and a recycling rewards program.',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    github: 'https://github.com/ecoshop',
    demo: 'https://ecoshop.com',
    image: 'https://picsum.photos/seed/EcoShop/400/300',
  },
  {
    title: 'SecureChat',
    description: 'An ultra-secure messaging app with end-to-end encryption, self-destructing messages, and blockchain-based user verification.',
    tech: ['Vue.js', 'Firebase', 'WebRTC'],
    github: 'https://github.com/securechat',
    demo: 'https://securechat.app',
    image: 'https://picsum.photos/seed/SecureChat/400/300',
  },
  {
    title: 'MedVision AI',
    description: 'An advanced medical imaging analysis tool using deep learning for early disease detection and personalized treatment planning.',
    tech: ['Python', 'TensorFlow', 'Flask'],
    github: 'https://github.com/medvision-ai',
    demo: 'https://medvision.ai',
    image: 'https://picsum.photos/seed/MedVisionAI/400/300',
  },
  {
    title: 'SupplyChain+',
    description: 'A decentralized supply chain management platform with real-time tracking, smart contract automation, and predictive analytics for inventory optimization.',
    tech: ['Solidity', 'Ethereum', 'Web3.js'],
    github: 'https://github.com/supplychain-plus',
    demo: 'https://supplychain-plus.io',
    image: 'https://picsum.photos/seed/SupplyChainPlus/400/300',
  },
  {
    title: 'SmartHome Hub',
    description: 'A centralized IoT platform for managing smart home devices, featuring voice control, energy optimization, and predictive maintenance.',
    tech: ['React Native', 'AWS IoT', 'GraphQL'],
    github: 'https://github.com/smarthome-hub',
    demo: 'https://smarthome-hub.io',
    image: 'https://picsum.photos/seed/SmartHomeHub/400/300',
  },
  {
    title: 'FitnessFusion',
    description: 'An AI-powered fitness app offering personalized workout plans, nutrition tracking, and virtual reality training sessions.',
    tech: ['Flutter', 'TensorFlow Lite', 'Firebase'],
    github: 'https://github.com/fitnessfusion',
    demo: 'https://fitnessfusion.app',
    image: 'https://picsum.photos/seed/FitnessFusion/400/300',
  },
  {
    title: 'CryptoTax',
    description: 'A cryptocurrency tax calculation and reporting tool, supporting multiple exchanges and providing real-time tax liability estimates.',
    tech: ['Angular', 'Node.js', 'PostgreSQL'],
    github: 'https://github.com/cryptotax',
    demo: 'https://cryptotax.io',
    image: 'https://picsum.photos/seed/CryptoTax/400/300',
  },
  {
    title: 'EduQuest',
    description: 'An interactive e-learning platform with gamification elements, adaptive learning paths, and real-time collaboration features.',
    tech: ['React', 'Express.js', 'MongoDB'],
    github: 'https://github.com/eduquest',
    demo: 'https://eduquest.com',
    image: 'https://picsum.photos/seed/EduQuest/400/300',
  },
  {
    title: 'GreenCity',
    description: 'A smart city management system focusing on sustainability, featuring pollution monitoring, waste management optimization, and citizen engagement tools.',
    tech: ['Vue.js', 'Django', 'PostgreSQL'],
    github: 'https://github.com/greencity',
    demo: 'https://greencity.io',
    image: 'https://picsum.photos/seed/GreenCity/400/300',
  },
  {
    title: 'ArtificialMind',
    description: 'A cutting-edge artificial general intelligence research platform, combining neural networks, evolutionary algorithms, and cognitive architectures.',
    tech: ['Python', 'PyTorch', 'Ray'],
    github: 'https://github.com/artificialmind',
    demo: 'https://artificialmind.ai',
    image: 'https://picsum.photos/seed/ArtificialMind/400/300',
  }
]
